### ISSUE TITLE
LGPL vs GPL

### ISSUE THREAD

**Issue by hmaarrfk** [conda-forge/pulseaudio-feedstock#31]
### Comment:

For FFMPEG, we have two builds, one with GPL, one for LGPL.

it is understood that the LGPL build may have fewer features, but it helps other packages retain their choice of license.

What do you think about a similar think for pulseaudio?

FYI: It seems that fftw is used for equalizers. https://www.linuxfromscratch.org/blfs/view/svn/multimedia/pulseaudio.html

xref: https://github.com/conda-forge/ffmpeg-feedstock/pull/138

**Comment by ryanvolz** [comment]
I don't feel strongly about this. Reading [this](https://cgit.freedesktop.org/pulseaudio/pulseaudio/tree/LICENSE), I guess we're already shipping a GPL combined work because of linking with `fftw`? Is there anything downstream that actually cares about the license `pulseaudio` is using?

It seems to me that the licensing is mainly a concern of the upstream developers, and as packagers (or for the users) we don't care as much as long as the license gives us permission to distribute. The only benefit I see to having a pure LGPL `pulseaudio` is if there is a downstream package where the author has decided they want to avoid GPL but still needs to use `pulseaudio` and we can only package that software if there is a pure LGPL `pulseaudio`.

So if there's a benefit like that, absolutely! If not, I don't see the point but I'd still merge it anyway if someone wants it.

**Comment by hmaarrfk** [comment]
the qt package is my concern. I would like to have an LGPL version of qt.

**Comment by hmaarrfk** [comment]
hmm, i didn't realize that this library was only for the pulseaudio server. Maybe the better solution is to split this package as "server" and "client" since according to your link, the client presuably does not need the fftw  library

**Comment by ryanvolz** [comment]
Gotcha. Then I'm good with that. I was just about to bring up the server aspect, saying that I don't really know if anyone actually uses it from conda-forge or if the main benefit of this package is the library/client. I'm definitely open to splitting into multiple outputs, especially if that helps clarify licensing.
